  /// \file ThreeVector.h
/*
 *
 * ThreeVector.h header template automatically generated by a class generator
 * Creation date : mar. janv. 6 2015
 *
 * This file is part of SDHCAL libraries.
 * 
 * SDHCAL is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 * 
 * SDHCAL is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with SDHCAL.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * @author rete
 * @copyright CNRS , IPNL
 */

#ifndef THREEVECTOR_HH
#define THREEVECTOR_HH

#include "CLHEP/Vector/ThreeVector.h"

typedef CLHEP::Hep3Vector ThreeVector;

#endif  //  LINEAR3DFIT_H
